// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace gui
{
	public partial class TeaacherViewController : NSView
	{
		public TeaacherViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
